### ISSUE TITLE
[Bug] Toggling Loader Mem Compat causes crash

### ISSUE THREAD

**Issue by flanter21** [xzn/ntr-hr#1]
As title. Tested on 0.1.2.1

**Comment by xzn** [comment]
Wow this one took forever to find, somehow my code got compiled to something that gets patched by this:

https://github.com/xzn/BootNTR/blob/158609a1fcff950fdc0b3325c3b98e636494addf/source/pathPatcher.c#L89

Should be fixed soon..

**Comment by xzn** [comment]
Thanks update released!
