### ISSUE TITLE
[Bug] Lost the lower screen after soft resets

### ISSUE THREAD

**Issue by u93132** [xzn/ntr-hr#2]
The NTR-HR stopped sending the packets related to the lower screens after soft resets. This issue can only be fixed by restarting the 3DS. Reconnecting doesn't help.

I checked by using NTRviewer and also analyzed the packets. This issue did not exist in 20240106 and started to show up at least after 20240125 (not sure which one specifically.)

**Comment by xzn** [comment]
Have you tried v0.1.6 or later? I've fixed a race condition in v0.1.6 (I think) not sure if it will help with this specific issue.

**Comment by u93132** [comment]
Yeah, I tested on 0.1.6. It works well first, but later on I still lost the lower screen. Is there anything I can do to help you debug?

**Comment by xzn** [comment]
After staring at the source code I think I've found the bug. (Somewhere in screen priority code it can return early before consistent state is reached. To fix it just need to make things less complicated)

I'll release an update in a moment.

For now try reconnecting with different parameters (say changing quality from 75 to 80) to force a refresh of all the encoding variables and threads. (Just reconnecting doesn't do anything if options aren't changed)

That should at least get the screens back as a workaround. (I'll be very confused if this doesn't work as remote play now resets everything on parameter change.)

**Comment by xzn** [comment]
Here: https://github.com/xzn/ntr-hr/releases/tag/v0.1.6.2

Will close this issue if I don't hear more about this from in a few days (assuming that means everything is good haha.)

Edit: I think I forgot to update the version number in BootNTR, so after installing make sure to delete the old `/3ds/BootNTRSelector` files

**Comment by u93132** [comment]
I believe this one is fixed.
