### ISSUE TITLE
Multiple Console Issues

### ISSUE THREAD

**Issue by VashEXE** [xzn/ntr-hr#5]
**Hardware:**
New 2DS XL x4

**Software:**
Luma 13.1.1
NTR-HR 0.2.1.1
 BootNTRSelector-PabloMK7-Banner.cia 

I've had a problem when using NTR-HR with multiple consoles at the same time. It doesn't appear that I can patch the NTR-HR files with Snickerstream. Is there any way to adjust the port that NTR-HR is using for RemotePlay like 3.6 had with the Snickerstream patching? I've also attempted to set the port from the X+Y Menu, and while it connects, I see a bunch of traffic on Port 8000 when looking at Wireshark. I'm thinking that potentially there is some port congestion on port 8000, is that something I can adjust?

I've been able to get 4 consoles streaming at the same time, but the FPS drops sharply when the 3rd and 4th are connected. It happens even before Snickerstream is connected actually. If I have 1 console streaming with Snickerstream and just open the socket for remoteplay on the other 3, it will drop the 1 streaming console from 60fps to 4fps every time. 

Any help would be greatly appreciated. I'd be happy to provide any other info as well.

**Comment by xzn** [comment]
Port 8000 is used for the initial connection setup and shouldn't affect the streaming performance.

Since you were able to get four N3DS running simultaneously, try going into the X+Y menu and change the bandwidth limit to something low, like 0.5 mbps, and the quality can be lowered as well, (say around 50).

I don't know how to get a higher framerate without using multiple wifi APs, but it shouldn't be so low as 4 fps.. I'd expect that with 4 devices, it should be around 20 to 25 fps for each device.

**Comment by VashEXE** [comment]
So just to be clear, using multiple APs for the connections of the 3DS will help with performance? I could throw an AP on just to test that.

When 4x devices are connected, it's pretty strange. One will run at 60fps, 2 will run around 27fps, and the 1st one to have a socket opened will drop to single digits consistently. Very strange.

**Comment by xzn** [comment]
Multiple APs running on different channels should allow better throughput overall, hopefully. Remoteplay just sends udp packets to the specified IP and port blindly, I'm not sure how some kind of congestion control can be implemented..

**Comment by VashEXE** [comment]
2nd AP doesn't seem to make a difference for me. In the HR Viewer I see serious packet loss when a 3rd is connected and even more when a 4th is.

Looks like this might just be a limitation of UDP without QUIC or something to assist with validation of the traffic. Either way, thanks for your quick replies.
